language: ruby

script: bundle exec rake spec

rvm:
  - ruby-head
  - 2.3.0
  - 2.2.3
  - 2.1.7
  - 2.0
  - 1.9.3

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  email:
    recipients:
      - ngiger@ywesee.com

cache: bundler
sudo: false
